#!/bin/bash

# this is called array, instead of single value it can hold mutiple values.
PERSONS=("ramesh" "suresh" "Sachin")

echo "First Person: ${PERSON[0]}"

echo "First Person: ${PERSON[@]}" # @ means all the peoples.