#!/bin/bash

# this is called array, instead of single value it can hold mutiple values.
PERSONS=("ramesh" "suresh" "Sachin")

echo "First Person: ${PERSONS[0]}"

echo "All Persons: ${PERSONS[@]}" # @ means all the peoples.